# This workflow automatically deploys the web app to the official url
# when new changes are pushed to main branch (after package version update).

name: Production deploy

on:
  workflow_run:
    workflows: ["Update Package Version"]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ vars.FRONTEND_WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPENSTRENGTH }}"
          channelId: live
          projectId: openstrength
